import { AllProduct, Filters, Product } from "./product.type";

export const products: Product[] = [
  // B2C Retail Products
  {
    id: 1,
    name: "BetterBody Foods Organic Chia",
    image: "/product/product1.png",
    price: "$33.00",
    oldPrice: "$55.00",
    rating: 0,
    discount: 40,
    sale: true,
  },
  {
    id: 2,
    name: "Birds Eye 22 Crispy Chicken Dippers",
    image: "/product/product2.png",
    price: "$19.20",
    oldPrice: "$32.00",
    rating: 5,
    discount: 40,
  },
  {
    id: 3,
    name: "Goodfella’s Stone Baked Thin Pizza",
    image: "/product/product3.png",
    price: "$9.00",
    oldPrice: "$15.00",
    rating: 4,
    discount: 40,
  },
  {
    id: 4,
    name: "Low Sodium Lightly Salted Snack Nuts",
    image: "/product/product4.png",
    price: "$32.40",
    oldPrice: "$54.00",
    rating: 0,
    discount: 40,
    sale: true,
  },
  {
    id: 5,
    name: "Morrisons The Best Jumbo King Prawns",
    image: "/product/product5.png",
    price: "$13.80",
    oldPrice: "$23.00",
    rating: 0,
    discount: 40,
    sale: true,
  },
  {
    id: 6,
    name: "Quaker Chewy Granola Bars",
    image: "/product/product6.png",
    price: "$39.00",
    oldPrice: "$65.00",
    rating: 0,
    discount: 40,
    sale: true,
  },
  // B2B Wholesale Products
  {
    id: "p1",
    title: "Fresh Organic Carrots — Bulk Export Grade A",
    price: "BDT 38.00 / kg",
    moq: "Min. order: 500 kg",
    supplier: "GreenField Agro Traders",
    countryCode: "bd",
    years: 4,
    verified: true,
    category: "vegetables",
  },
  {
    id: "p2",
    title: "Wireless Bluetooth Earbuds — OEM Custom Branding",
    price: "BDT 620.00",
    oldPrice: "BDT 780.00",
    moq: "Min. order: 100 pieces",
    supplier: "Shenzhen Voxtech Electronics",
    countryCode: "cn",
    years: 8,
    rating: 4.7,
    reviews: 132,
    super: true,
    verified: true,
    category: "electronics",
  },
  {
    id: "p3",
    title: "Cotton Woven Fabric Roll — Wholesale Textile Supply",
    price: "BDT 210.00 / m",
    moq: "Min. order: 1,000 m",
    supplier: "Dhaka Textile Mills Ltd.",
    countryCode: "bd",
    years: 12,
    rating: 4.8,
    reviews: 54,
    verified: true,
    category: "textiles",
  },
  {
    id: "p4",
    title: "Industrial CNC Milling Machine — Heavy Duty",
    price: "BDT 1,240,000.00",
    moq: "Min. order: 1 unit",
    supplier: "Precision Tools Manufacturing",
    countryCode: "cn",
    years: 15,
    verified: true,
    category: "machinery",
  },
  {
    id: "p5",
    title: "Non-Stick Cookware Set — 7 Piece Kitchen Bundle",
    price: "BDT 1,850.00",
    moq: "Min. order: 50 sets",
    supplier: "Homeline Kitchenware Co.",
    countryCode: "in",
    years: 6,
    rating: 4.5,
    reviews: 41,
    verified: true,
    category: "home-kitchen",
  },
  {
    id: "p6",
    title: "NPK Fertilizer Granules — Agricultural Grade",
    price: "BDT 42.00 / kg",
    moq: "Min. order: 2,000 kg",
    supplier: "AgroChem Solutions",
    countryCode: "pk",
    years: 9,
    verified: false,
    category: "agriculture",
  },
  {
    id: "p7",
    title: "LED Headlight Assembly — Universal Fit Auto Parts",
    price: "BDT 1,120.00",
    moq: "Min. order: 200 pieces",
    supplier: "AutoBright Components",
    countryCode: "th",
    years: 5,
    rating: 4.6,
    reviews: 23,
    verified: true,
    category: "automotive",
  },
  {
    id: "p8",
    title: "Herbal Face Serum — Private Label Skincare",
    price: "BDT 340.00",
    moq: "Min. order: 300 units",
    supplier: "Botanix Beauty Labs",
    countryCode: "vn",
    years: 3,
    rating: 4.9,
    reviews: 18,
    verified: true,
    category: "beauty",
  },
];

export const SingleProduct = {
  name: "Fresh For The Bold Ground Amazon",
  price: "$12.00",
  image: "/product/product3.png",
  description:
    "Discover premium quality products from trusted suppliers. Perfect for businesses looking for reliable wholesale products at competitive prices.",
  sku: "BF002-1-1",
  category: "Organic Foods",
  supplier: "Markood Verified Supplier",
  companyName: "Sagor Company",
  CompanyLogo: "/logo/fevicon.svg",
};

export const priceTiers = [
  {
    quantity: "< 10",
    price: "$12.00",
  },
  {
    quantity: "10 - 19",
    price: "$11.40",
  },
  {
    quantity: "20 - 49",
    price: "$10.80",
  },
  {
    quantity: "50 - 99",
    price: "$9.60",
  },
  {
    quantity: "100+",
    price: "$9.00",
  },
];
export const thumbnails = [
  "/product/product1.png",
  "/product/product2.png",
  "/product/product3.png",
  "/product/product4.png",
];

export const PROVIDERS = [
  {
    name: "Tech World BD",
    category: "Electronics",
    location: "Dhaka, Bangladesh",
    rating: "4.8",
    products: 245,
    orders: "1.2K+",
    verified: true,
  },
  {
    name: "Fresh Supply Co.",
    category: "Food & Grocery",
    location: "Chattogram, Bangladesh",
    rating: "4.7",
    products: 180,
    orders: "950+",
    verified: true,
  },
  {
    name: "Style Hub",
    category: "Fashion & Apparel",
    location: "Dhaka, Bangladesh",
    rating: "4.6",
    products: 320,
    orders: "2.1K+",
    verified: true,
  },
  {
    name: "Home Essentials",
    category: "Home & Living",
    location: "Narayanganj, Bangladesh",
    rating: "4.5",
    products: 156,
    orders: "780+",
    verified: false,
  },
  {
    name: "Agro Trade BD",
    category: "Agriculture",
    location: "Rajshahi, Bangladesh",
    rating: "4.8",
    products: 210,
    orders: "1.5K+",
    verified: true,
  },
  {
    name: "Auto Parts Center",
    category: "Automotive",
    location: "Dhaka, Bangladesh",
    rating: "4.6",
    products: 198,
    orders: "890+",
    verified: true,
  },
];
export type Country = {
  code: string;
  name: string;
  flag: string;
  count: number;
};

export const countries: Country[] = [
  { code: "bd", name: "Bangladesh", flag: "🇧🇩", count: 482 },
  { code: "in", name: "India", flag: "🇮🇳", count: 356 },
  { code: "cn", name: "China", flag: "🇨🇳", count: 291 },
  { code: "vn", name: "Vietnam", flag: "🇻🇳", count: 128 },
  { code: "pk", name: "Pakistan", flag: "🇵🇰", count: 97 },
  { code: "th", name: "Thailand", flag: "🇹🇭", count: 64 },
  { code: "tr", name: "Turkey", flag: "🇹🇷", count: 41 },
];

export type Category = {
  slug: string;
  name: string;
  icon: string; // lucide-react icon name
};

export const categories: Category[] = [
  { slug: "vegetables", name: "Vegetables & Fruits", icon: "Carrot" },
  { slug: "electronics", name: "Electronics", icon: "Cpu" },
  { slug: "textiles", name: "Textiles & Apparel", icon: "Shirt" },
  { slug: "machinery", name: "Machinery & Tools", icon: "Cog" },
  { slug: "home-kitchen", name: "Home & Kitchen", icon: "Sofa" },
  { slug: "agriculture", name: "Agriculture Supplies", icon: "Wheat" },
  { slug: "automotive", name: "Automotive Parts", icon: "Car" },
  { slug: "beauty", name: "Beauty & Personal Care", icon: "Sparkles" },
];

export const Allproducts: AllProduct[] = [
  {
    id: "p1",
    name: "Fresh Organic Carrots — Bulk Export Grade A",
    image: "/products/carrots.jpg",
    price: "BDT 38.00 / kg",
    rating: 4.4,
    reviews: 12,
    isNew: true,
    category: "vegetables",
    countryCode: "bd",
    verified: true,
    moq: "Min. order: 500 kg",
    supplier: "GreenField Agro Traders",
    supplierImage: "/suppliers/greenfield.jpg",
    years: 4,
    isTopProduct: true,
  },
  {
    id: "p2",
    name: "Wireless Bluetooth Earbuds — OEM Custom Branding",
    image: "/products/earbuds.jpg",
    isBestSeller: true,
    price: "BDT 620.00",
    oldPrice: "BDT 780.00",
    sale: true,
    rating: 4.7,
    reviews: 132,
    category: "electronics",
    countryCode: "cn",
    verified: true,
    moq: "Min. order: 100 pieces",
    supplier: "Shenzhen Voxtech Electronics",
    supplierImage: "/suppliers/voxtech.jpg",
    years: 8,
    isTopProduct: true,
  },
  {
    id: "p3",
    name: "Cotton Woven Fabric Roll — Wholesale Textile Supply",
    image: "/products/fabric.jpg",
    price: "BDT 210.00 / m",
    rating: 4.8,
    reviews: 54,
    isNew: true,
    category: "textiles",
    countryCode: "bd",
    verified: true,
    moq: "Min. order: 1,000 m",
    supplier: "Dhaka Textile Mills Ltd.",
    supplierImage: "/suppliers/dhaka-textile.jpg",
    years: 12,
  },
  {
    id: "p4",
    name: "Industrial CNC Milling Machine — Heavy Duty",
    image: "/products/cnc-machine.jpg",
    price: "BDT 1,240,000.00",
    rating: 4.2,
    reviews: 7,
    category: "machinery",
    countryCode: "cn",
    verified: true,
    moq: "Min. order: 1 unit",
    supplier: "Precision Tools Manufacturing",
    supplierImage: "/suppliers/precision-tools.jpg",
    years: 15,
    isTopProduct: true,
  },
  {
    id: "p5",
    name: "Non-Stick Cookware Set — 7 Piece Kitchen Bundle",
    image: "/products/cookware.jpg",
    isNew: true,
    price: "BDT 1,850.00",
    sale: true,
    rating: 4.5,
    reviews: 41,
    category: "home-kitchen",
    countryCode: "in",
    verified: true,
    isBestSeller: true,
    moq: "Min. order: 50 sets",
    supplier: "Homeline Kitchenware Co.",
    supplierImage: "/suppliers/homeline.jpg",
    years: 6,
  },
  {
    id: "p6",
    name: "NPK Fertilizer Granules — Agricultural Grade",
    image: "/products/fertilizer.jpg",
    price: "BDT 42.00 / kg",
    rating: 4.0,
    reviews: 9,
    category: "agriculture",
    countryCode: "pk",
    isNew: true,
    verified: false,
    moq: "Min. order: 2,000 kg",
    supplier: "AgroChem Solutions",
    supplierImage: "/suppliers/agrochem.jpg",
    years: 9,
    isTopProduct: true,
  },
  {
    id: "p7",
    name: "LED Headlight Assembly — Universal Fit Auto Parts",
    image: "/products/headlight.jpg",
    price: "BDT 1,120.00",
    isBestSeller: true,
    rating: 4.6,
    reviews: 23,
    category: "automotive",
    countryCode: "th",
    verified: true,
    moq: "Min. order: 200 pieces",
    supplier: "AutoBright Components",
    supplierImage: "/suppliers/autobright.jpg",
    years: 5,
  },
  {
    id: "p8",
    name: "Herbal Face Serum — Private Label Skincare",
    image: "/products/serum.jpg",
    price: "BDT 340.00",
    rating: 4.9,
    reviews: 18,
    category: "beauty",
    countryCode: "vn",
    verified: true,
    moq: "Min. order: 300 units",
    supplier: "Botanix Beauty Labs",
    supplierImage: "/suppliers/botanix.jpg",
    years: 3,
  },
];

export const initialFilters: Filters = {
  countryCodes: [],
  categorySlug: null,
  verifiedOnly: false,
  minRating: null,
  minPrice: "",
  maxPrice: "",
};
